name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Powershell version
      run: Write-Host "Powershell version:" $PSVersionTable.PSVersion

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore OfficeToPDF.sln
 
    - name: Build
      run: msbuild --% /target:Build /property:Platform="Any CPU";Configuration=Release /verbosity:minimal /m OfficeToPDF.sln

    - name: Test
      run: '& "./packages/NUnit.ConsoleRunner.3.15.0/tools/nunit3-console.exe" --skipnontestassemblies --config=Release --result="TestResults.xml;transform=nunit3-junit.xslt" OfficeToPDF.sln'

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()  # run this step even if previous step failed
      with:
        name: results             # Name of the check run which will be created
        path: TestResults.xml     # Path to test results
        reporter: java-junit